# Generated by Django 5.0.7 on 2024-07-23 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 7, 23, 8, 57, 31, 884364, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
